#pragma once

// For NULL
#include <cstdio>

#include "ArrayTy.h"
#include "BoolLiteral.h"
#include "Branch.h"
#include "CardExpr.h"
#include "Clause.h"
#include "ConstSymbol.h"
#include "DistrDefn.h"
#include "Distribution.h"
#include "DoubleLiteral.h"
#include "Expr.h"
#include "Evidence.h"
#include "FuncDefn.h"
#include "FunctionCall.h"
#include "IfThen.h"
#include "InstSymbol.h"
#include "IntLiteral.h"
#include "MapExpr.h"
#include "MapTy.h"
#include "NameTy.h"
#include "NullSymbol.h"
#include "NumberStmt.h"
#include "OprExpr.h"
#include "OriginAttr.h"
#include "OriginRefer.h"
#include "QuantForm.h"
#include "StringLiteral.h"
#include "Ty.h"
#include "TypeDomain.h"
#include "VarDecl.h"
#include "VarRefer.h"
#include "VoidFuncCall.h"